# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.payment_executor import payment_executor_pb2 as utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2


class PaymentExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePayment = channel.unary_unary(
                '/payment_executor.PaymentExecutorService/ExecutePayment',
                request_serializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.PaymentExecutionRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.PaymentExecutionResponse.FromString,
                )
        self.SendVoteToCoordinator = channel.unary_unary(
                '/payment_executor.PaymentExecutorService/SendVoteToCoordinator',
                request_serializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.VoteCommitRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.VoteCommitResponse.FromString,
                )


class PaymentExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVoteToCoordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePayment,
                    request_deserializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.PaymentExecutionRequest.FromString,
                    response_serializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.PaymentExecutionResponse.SerializeToString,
            ),
            'SendVoteToCoordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVoteToCoordinator,
                    request_deserializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.VoteCommitRequest.FromString,
                    response_serializer=utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.VoteCommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment_executor.PaymentExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_executor.PaymentExecutorService/ExecutePayment',
            utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.PaymentExecutionRequest.SerializeToString,
            utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.PaymentExecutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendVoteToCoordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_executor.PaymentExecutorService/SendVoteToCoordinator',
            utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.VoteCommitRequest.SerializeToString,
            utils_dot_pb_dot_payment__executor_dot_payment__executor__pb2.VoteCommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
